/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApiExplainer: typeof import('./src/components/ApiExplainer.vue')['default']
    ApiStatus: typeof import('./src/components/ApiStatus.vue')['default']
    BaseDemo: typeof import('./src/components/BaseDemo.vue')['default']
    CodeExample: typeof import('./src/components/CodeExample.vue')['default']
    ExamplePrompts: typeof import('./src/components/ExamplePrompts.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    HistoryPanel: typeof import('./src/components/HistoryPanel.vue')['default']
    LanguageDetectorDemo: typeof import('./src/views/LanguageDetectorDemo.vue')['default']
    ParameterControls: typeof import('./src/components/ParameterControls.vue')['default']
    PerformanceMetrics: typeof import('./src/components/PerformanceMetrics.vue')['default']
    ProcessingState: typeof import('./src/components/ProcessingState.vue')['default']
    ResultDisplay: typeof import('./src/components/ResultDisplay.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShareButton: typeof import('./src/components/ShareButton.vue')['default']
    StreamingToggle: typeof import('./src/components/StreamingToggle.vue')['default']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
    UAlert: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Alert.vue')['default']
    UBadge: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UCheckbox: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue')['default']
    UIcon: typeof import('./node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UProgress: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Progress.vue')['default']
    USelect: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USelectMenu: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/SelectMenu.vue')['default']
    USlider: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Slider.vue')['default']
    USwitch: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Switch.vue')['default']
    UTextarea: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
  }
}
